<?php
/**
 * ProductForm
 *
 * PHP version 5
 *
 * @category Class
 * @package  RackbeatApp\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Rackbeat
 *
 * If you're interested in demo access, contact us below and we will setup a temporary account for you. Alternatively you can sign up through our site and skip the billing step.
 *
 * OpenAPI spec version: 0.5.4
 * Contact: tech@rackbeat.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace RackbeatApp\Client\Model;

use ArrayAccess;
use RackbeatApp\Client\ObjectSerializer;

/**
 * ProductForm Class Doc Comment
 *
 * @category Class
 * @package     RackbeatApp\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ProductForm implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'product_form';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'number' => 'string',
        'barcode' => 'string',
        'name' => 'string',
        'sales_price' => 'float',
        'recommended_cost_price' => 'float',
        'min_order' => 'int',
        'min_stock' => 'int',
        'stock_quantity' => 'int',
        'group' => 'int',
        'group_id' => 'int',
        'default_location_id' => 'int',
        'unit' => 'string',
        'unit_id' => 'int',
        'variation_id' => 'int',
        'physical_weight' => 'float',
        'physical_height' => 'float',
        'physical_width' => 'float',
        'physical_depth' => 'float',
        'physical_weight_unit' => 'string',
        'physical_size_unit' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'number' => null,
        'barcode' => null,
        'name' => null,
        'sales_price' => null,
        'recommended_cost_price' => null,
        'min_order' => null,
        'min_stock' => null,
        'stock_quantity' => null,
        'group' => 'int10',
        'group_id' => 'int10',
        'default_location_id' => 'int10',
        'unit' => null,
        'unit_id' => 'int10',
        'variation_id' => null,
        'physical_weight' => null,
        'physical_height' => null,
        'physical_width' => null,
        'physical_depth' => null,
        'physical_weight_unit' => null,
        'physical_size_unit' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'number' => 'number',
        'barcode' => 'barcode',
        'name' => 'name',
        'sales_price' => 'sales_price',
        'recommended_cost_price' => 'recommended_cost_price',
        'min_order' => 'min_order',
        'min_stock' => 'min_stock',
        'stock_quantity' => 'stock_quantity',
        'group' => 'group',
        'group_id' => 'group_id',
        'default_location_id' => 'default_location_id',
        'unit' => 'unit',
        'unit_id' => 'unit_id',
        'variation_id' => 'variation_id',
        'physical_weight' => 'physical.weight',
        'physical_height' => 'physical.height',
        'physical_width' => 'physical.width',
        'physical_depth' => 'physical.depth',
        'physical_weight_unit' => 'physical.weight_unit',
        'physical_size_unit' => 'physical.size_unit'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'number' => 'setNumber',
        'barcode' => 'setBarcode',
        'name' => 'setName',
        'sales_price' => 'setSalesPrice',
        'recommended_cost_price' => 'setRecommendedCostPrice',
        'min_order' => 'setMinOrder',
        'min_stock' => 'setMinStock',
        'stock_quantity' => 'setStockQuantity',
        'group' => 'setGroup',
        'group_id' => 'setGroupId',
        'default_location_id' => 'setDefaultLocationId',
        'unit' => 'setUnit',
        'unit_id' => 'setUnitId',
        'variation_id' => 'setVariationId',
        'physical_weight' => 'setPhysicalWeight',
        'physical_height' => 'setPhysicalHeight',
        'physical_width' => 'setPhysicalWidth',
        'physical_depth' => 'setPhysicalDepth',
        'physical_weight_unit' => 'setPhysicalWeightUnit',
        'physical_size_unit' => 'setPhysicalSizeUnit'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'number' => 'getNumber',
        'barcode' => 'getBarcode',
        'name' => 'getName',
        'sales_price' => 'getSalesPrice',
        'recommended_cost_price' => 'getRecommendedCostPrice',
        'min_order' => 'getMinOrder',
        'min_stock' => 'getMinStock',
        'stock_quantity' => 'getStockQuantity',
        'group' => 'getGroup',
        'group_id' => 'getGroupId',
        'default_location_id' => 'getDefaultLocationId',
        'unit' => 'getUnit',
        'unit_id' => 'getUnitId',
        'variation_id' => 'getVariationId',
        'physical_weight' => 'getPhysicalWeight',
        'physical_height' => 'getPhysicalHeight',
        'physical_width' => 'getPhysicalWidth',
        'physical_depth' => 'getPhysicalDepth',
        'physical_weight_unit' => 'getPhysicalWeightUnit',
        'physical_size_unit' => 'getPhysicalSizeUnit'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['number'] = isset($data['number']) ? $data['number'] : null;
        $this->container['barcode'] = isset($data['barcode']) ? $data['barcode'] : null;
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['sales_price'] = isset($data['sales_price']) ? $data['sales_price'] : null;
        $this->container['recommended_cost_price'] = isset($data['recommended_cost_price']) ? $data['recommended_cost_price'] : null;
        $this->container['min_order'] = isset($data['min_order']) ? $data['min_order'] : null;
        $this->container['min_stock'] = isset($data['min_stock']) ? $data['min_stock'] : null;
        $this->container['stock_quantity'] = isset($data['stock_quantity']) ? $data['stock_quantity'] : null;
        $this->container['group'] = isset($data['group']) ? $data['group'] : null;
        $this->container['group_id'] = isset($data['group_id']) ? $data['group_id'] : null;
        $this->container['default_location_id'] = isset($data['default_location_id']) ? $data['default_location_id'] : null;
        $this->container['unit'] = isset($data['unit']) ? $data['unit'] : null;
        $this->container['unit_id'] = isset($data['unit_id']) ? $data['unit_id'] : null;
        $this->container['variation_id'] = isset($data['variation_id']) ? $data['variation_id'] : null;
        $this->container['physical_weight'] = isset($data['physical_weight']) ? $data['physical_weight'] : null;
        $this->container['physical_height'] = isset($data['physical_height']) ? $data['physical_height'] : null;
        $this->container['physical_width'] = isset($data['physical_width']) ? $data['physical_width'] : null;
        $this->container['physical_depth'] = isset($data['physical_depth']) ? $data['physical_depth'] : null;
        $this->container['physical_weight_unit'] = isset($data['physical_weight_unit']) ? $data['physical_weight_unit'] : null;
        $this->container['physical_size_unit'] = isset($data['physical_size_unit']) ? $data['physical_size_unit'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['number'] === null) {
            $invalidProperties[] = "'number' can't be null";
        }
        if ((strlen($this->container['number']) > 50)) {
            $invalidProperties[] = "invalid value for 'number', the character length must be smaller than or equal to 50.";
        }

        if (!is_null($this->container['barcode']) && (strlen($this->container['barcode']) > 50)) {
            $invalidProperties[] = "invalid value for 'barcode', the character length must be smaller than or equal to 50.";
        }

        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ((strlen($this->container['name']) > 80)) {
            $invalidProperties[] = "invalid value for 'name', the character length must be smaller than or equal to 80.";
        }

        if ($this->container['sales_price'] === null) {
            $invalidProperties[] = "'sales_price' can't be null";
        }
        if (!is_null($this->container['unit']) && (strlen($this->container['unit']) > 50)) {
            $invalidProperties[] = "invalid value for 'unit', the character length must be smaller than or equal to 50.";
        }

        if (!is_null($this->container['physical_weight_unit']) && (strlen($this->container['physical_weight_unit']) > 30)) {
            $invalidProperties[] = "invalid value for 'physical_weight_unit', the character length must be smaller than or equal to 30.";
        }

        if (!is_null($this->container['physical_size_unit']) && (strlen($this->container['physical_size_unit']) > 30)) {
            $invalidProperties[] = "invalid value for 'physical_size_unit', the character length must be smaller than or equal to 30.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        if ($this->container['number'] === null) {
            return false;
        }
        if (strlen($this->container['number']) > 50) {
            return false;
        }
        if (strlen($this->container['barcode']) > 50) {
            return false;
        }
        if ($this->container['name'] === null) {
            return false;
        }
        if (strlen($this->container['name']) > 80) {
            return false;
        }
        if ($this->container['sales_price'] === null) {
            return false;
        }
        if (strlen($this->container['unit']) > 50) {
            return false;
        }
        if (strlen($this->container['physical_weight_unit']) > 30) {
            return false;
        }
        if (strlen($this->container['physical_size_unit']) > 30) {
            return false;
        }
        return true;
    }


    /**
     * Gets number
     *
     * @return string
     */
    public function getNumber()
    {
        return $this->container['number'];
    }

    /**
     * Sets number
     *
     * @param string $number number
     *
     * @return $this
     */
    public function setNumber($number)
    {
        if ((strlen($number) > 50)) {
            throw new \InvalidArgumentException('invalid length for $number when calling ProductForm., must be smaller than or equal to 50.');
        }

        $this->container['number'] = $number;

        return $this;
    }

    /**
     * Gets barcode
     *
     * @return string
     */
    public function getBarcode()
    {
        return $this->container['barcode'];
    }

    /**
     * Sets barcode
     *
     * @param string $barcode barcode
     *
     * @return $this
     */
    public function setBarcode($barcode)
    {
        if (!is_null($barcode) && (strlen($barcode) > 50)) {
            throw new \InvalidArgumentException('invalid length for $barcode when calling ProductForm., must be smaller than or equal to 50.');
        }

        $this->container['barcode'] = $barcode;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return $this
     */
    public function setName($name)
    {
        if ((strlen($name) > 80)) {
            throw new \InvalidArgumentException('invalid length for $name when calling ProductForm., must be smaller than or equal to 80.');
        }

        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets sales_price
     *
     * @return float
     */
    public function getSalesPrice()
    {
        return $this->container['sales_price'];
    }

    /**
     * Sets sales_price
     *
     * @param float $sales_price sales_price
     *
     * @return $this
     */
    public function setSalesPrice($sales_price)
    {
        $this->container['sales_price'] = $sales_price;

        return $this;
    }

    /**
     * Gets recommended_cost_price
     *
     * @return float
     */
    public function getRecommendedCostPrice()
    {
        return $this->container['recommended_cost_price'];
    }

    /**
     * Sets recommended_cost_price
     *
     * @param float $recommended_cost_price recommended_cost_price
     *
     * @return $this
     */
    public function setRecommendedCostPrice($recommended_cost_price)
    {
        $this->container['recommended_cost_price'] = $recommended_cost_price;

        return $this;
    }

    /**
     * Gets min_order
     *
     * @return int
     */
    public function getMinOrder()
    {
        return $this->container['min_order'];
    }

    /**
     * Sets min_order
     *
     * @param int $min_order min_order
     *
     * @return $this
     */
    public function setMinOrder($min_order)
    {
        $this->container['min_order'] = $min_order;

        return $this;
    }

    /**
     * Gets min_stock
     *
     * @return int
     */
    public function getMinStock()
    {
        return $this->container['min_stock'];
    }

    /**
     * Sets min_stock
     *
     * @param int $min_stock min_stock
     *
     * @return $this
     */
    public function setMinStock($min_stock)
    {
        $this->container['min_stock'] = $min_stock;

        return $this;
    }

    /**
     * Gets stock_quantity
     *
     * @return int
     */
    public function getStockQuantity()
    {
        return $this->container['stock_quantity'];
    }

    /**
     * Sets stock_quantity
     *
     * @param int $stock_quantity stock_quantity
     *
     * @return $this
     */
    public function setStockQuantity($stock_quantity)
    {
        $this->container['stock_quantity'] = $stock_quantity;

        return $this;
    }

    /**
     * Gets group
     *
     * @return int
     */
    public function getGroup()
    {
        return $this->container['group'];
    }

    /**
     * Sets group
     *
     * @param int $group group
     *
     * @return $this
     */
    public function setGroup($group)
    {
        $this->container['group'] = $group;

        return $this;
    }

    /**
     * Gets group_id
     *
     * @return int
     */
    public function getGroupId()
    {
        return $this->container['group_id'];
    }

    /**
     * Sets group_id
     *
     * @param int $group_id group_id
     *
     * @return $this
     */
    public function setGroupId($group_id)
    {
        $this->container['group_id'] = $group_id;

        return $this;
    }

    /**
     * Gets default_location_id
     *
     * @return int
     */
    public function getDefaultLocationId()
    {
        return $this->container['default_location_id'];
    }

    /**
     * Sets default_location_id
     *
     * @param int $default_location_id default_location_id
     *
     * @return $this
     */
    public function setDefaultLocationId($default_location_id)
    {
        $this->container['default_location_id'] = $default_location_id;

        return $this;
    }

    /**
     * Gets unit
     *
     * @return string
     */
    public function getUnit()
    {
        return $this->container['unit'];
    }

    /**
     * Sets unit
     *
     * @param string $unit unit
     *
     * @return $this
     */
    public function setUnit($unit)
    {
        if (!is_null($unit) && (strlen($unit) > 50)) {
            throw new \InvalidArgumentException('invalid length for $unit when calling ProductForm., must be smaller than or equal to 50.');
        }

        $this->container['unit'] = $unit;

        return $this;
    }

    /**
     * Gets unit_id
     *
     * @return int
     */
    public function getUnitId()
    {
        return $this->container['unit_id'];
    }

    /**
     * Sets unit_id
     *
     * @param int $unit_id unit_id
     *
     * @return $this
     */
    public function setUnitId($unit_id)
    {
        $this->container['unit_id'] = $unit_id;

        return $this;
    }

    /**
     * Gets variation_id
     *
     * @return int
     */
    public function getVariationId()
    {
        return $this->container['variation_id'];
    }

    /**
     * Sets variation_id
     *
     * @param int $variation_id variation_id
     *
     * @return $this
     */
    public function setVariationId($variation_id)
    {
        $this->container['variation_id'] = $variation_id;

        return $this;
    }

    /**
     * Gets physical_weight
     *
     * @return float
     */
    public function getPhysicalWeight()
    {
        return $this->container['physical_weight'];
    }

    /**
     * Sets physical_weight
     *
     * @param float $physical_weight physical_weight
     *
     * @return $this
     */
    public function setPhysicalWeight($physical_weight)
    {
        $this->container['physical_weight'] = $physical_weight;

        return $this;
    }

    /**
     * Gets physical_height
     *
     * @return float
     */
    public function getPhysicalHeight()
    {
        return $this->container['physical_height'];
    }

    /**
     * Sets physical_height
     *
     * @param float $physical_height physical_height
     *
     * @return $this
     */
    public function setPhysicalHeight($physical_height)
    {
        $this->container['physical_height'] = $physical_height;

        return $this;
    }

    /**
     * Gets physical_width
     *
     * @return float
     */
    public function getPhysicalWidth()
    {
        return $this->container['physical_width'];
    }

    /**
     * Sets physical_width
     *
     * @param float $physical_width physical_width
     *
     * @return $this
     */
    public function setPhysicalWidth($physical_width)
    {
        $this->container['physical_width'] = $physical_width;

        return $this;
    }

    /**
     * Gets physical_depth
     *
     * @return float
     */
    public function getPhysicalDepth()
    {
        return $this->container['physical_depth'];
    }

    /**
     * Sets physical_depth
     *
     * @param float $physical_depth physical_depth
     *
     * @return $this
     */
    public function setPhysicalDepth($physical_depth)
    {
        $this->container['physical_depth'] = $physical_depth;

        return $this;
    }

    /**
     * Gets physical_weight_unit
     *
     * @return string
     */
    public function getPhysicalWeightUnit()
    {
        return $this->container['physical_weight_unit'];
    }

    /**
     * Sets physical_weight_unit
     *
     * @param string $physical_weight_unit physical_weight_unit
     *
     * @return $this
     */
    public function setPhysicalWeightUnit($physical_weight_unit)
    {
        if (!is_null($physical_weight_unit) && (strlen($physical_weight_unit) > 30)) {
            throw new \InvalidArgumentException('invalid length for $physical_weight_unit when calling ProductForm., must be smaller than or equal to 30.');
        }

        $this->container['physical_weight_unit'] = $physical_weight_unit;

        return $this;
    }

    /**
     * Gets physical_size_unit
     *
     * @return string
     */
    public function getPhysicalSizeUnit()
    {
        return $this->container['physical_size_unit'];
    }

    /**
     * Sets physical_size_unit
     *
     * @param string $physical_size_unit physical_size_unit
     *
     * @return $this
     */
    public function setPhysicalSizeUnit($physical_size_unit)
    {
        if (!is_null($physical_size_unit) && (strlen($physical_size_unit) > 30)) {
            throw new \InvalidArgumentException('invalid length for $physical_size_unit when calling ProductForm., must be smaller than or equal to 30.');
        }

        $this->container['physical_size_unit'] = $physical_size_unit;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param  integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param  integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param  integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}

