<?php
/**
 * BodyTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  RackbeatApp\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Rackbeat
 *
 * If you're interested in demo access, contact us below and we will setup a temporary account for you. Alternatively you can sign up through our site and skip the billing step.
 *
 * OpenAPI spec version: 0.5.4
 * Contact: tech@rackbeat.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace RackbeatApp\Client;

/**
 * BodyTest Class Doc Comment
 *
 * @category    Class */
// * @description Body
/**
 * @package     RackbeatApp\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BodyTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Body"
     */
    public function testBody()
    {
    }

    /**
     * Test attribute "number"
     */
    public function testPropertyNumber()
    {
    }

    /**
     * Test attribute "group"
     */
    public function testPropertyGroup()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "barcode"
     */
    public function testPropertyBarcode()
    {
    }

    /**
     * Test attribute "sales_price"
     */
    public function testPropertySalesPrice()
    {
    }

    /**
     * Test attribute "recommended_cost_price"
     */
    public function testPropertyRecommendedCostPrice()
    {
    }

    /**
     * Test attribute "min_order"
     */
    public function testPropertyMinOrder()
    {
    }

    /**
     * Test attribute "min_stock"
     */
    public function testPropertyMinStock()
    {
    }

    /**
     * Test attribute "stock_quantity"
     */
    public function testPropertyStockQuantity()
    {
    }

    /**
     * Test attribute "default_location_id"
     */
    public function testPropertyDefaultLocationId()
    {
    }

    /**
     * Test attribute "unit"
     */
    public function testPropertyUnit()
    {
    }

    /**
     * Test attribute "physical"
     */
    public function testPropertyPhysical()
    {
    }
}
