<?php
/**
 * CustomersApiTest
 * PHP version 5
 *
 * @category Class
 * @package  RackbeatApp\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Rackbeat
 *
 * If you're interested in demo access, contact us below and we will setup a temporary account for you. Alternatively you can sign up through our site and skip the billing step.
 *
 * OpenAPI spec version: 0.5.4
 * Contact: tech@rackbeat.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace RackbeatApp\Client;

/**
 * CustomersApiTest Class Doc Comment
 *
 * @category Class
 * @package  RackbeatApp\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CustomersApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for customerGroupProductsResetPrice
     *
     * Reset price of customer group product.
     *
     */
    public function testCustomerGroupProductsResetPrice()
    {
    }

    /**
     * Test case for customersPproductsResetPrice
     *
     * Reset price of customer product.
     *
     */
    public function testCustomersPproductsResetPrice()
    {
    }

    /**
     * Test case for deleteCustomer
     *
     * Delete existing customer.
     *
     */
    public function testDeleteCustomer()
    {
    }

    /**
     * Test case for indexCustomers
     *
     * Index customers.
     *
     */
    public function testIndexCustomers()
    {
    }

    /**
     * Test case for indexCustomersProducts
     *
     * Index customers.
     *
     */
    public function testIndexCustomersProducts()
    {
    }

    /**
     * Test case for shoeCustomerProduct
     *
     * Show customer product.
     *
     */
    public function testShoeCustomerProduct()
    {
    }

    /**
     * Test case for showCustomer
     *
     * Show single customer.
     *
     */
    public function testShowCustomer()
    {
    }

    /**
     * Test case for storeCustomer
     *
     * Create new customer.
     *
     */
    public function testStoreCustomer()
    {
    }

    /**
     * Test case for updateCustomer
     *
     * Update existing customer.
     *
     */
    public function testUpdateCustomer()
    {
    }

    /**
     * Test case for updateCustomerProduct
     *
     * Update customer product.
     *
     */
    public function testUpdateCustomerProduct()
    {
    }
}
