<?php
/**
 * ProductsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Rackbeat
 *
 * If you're interested in demo access, contact us below and we will setup a temporary account for you. Alternatively you can sign up through our site and skip the billing step.
 *
 * OpenAPI spec version: 0.5.4
 * Contact: tech@rackbeat.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * ProductsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ProductsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addProductImage
     *
     * Add product image.
     *
     */
    public function testAddProductImage()
    {
    }

    /**
     * Test case for deleteProduct
     *
     * Delete existing product.
     *
     */
    public function testDeleteProduct()
    {
    }

    /**
     * Test case for deleteProductImage
     *
     * Delete product image.
     *
     */
    public function testDeleteProductImage()
    {
    }

    /**
     * Test case for deleteProductVariationOption
     *
     * Delete existing product variation option.
     *
     */
    public function testDeleteProductVariationOption()
    {
    }

    /**
     * Test case for deleteProductsVariation
     *
     * Delete existing products variation.
     *
     */
    public function testDeleteProductsVariation()
    {
    }

    /**
     * Test case for deleteProductsVariationType
     *
     * Delete existing products variation type.
     *
     */
    public function testDeleteProductsVariationType()
    {
    }

    /**
     * Test case for getProductsTranslation
     *
     * Get product translation.
     *
     */
    public function testGetProductsTranslation()
    {
    }

    /**
     * Test case for getProductsTranslations
     *
     * Get product translation.
     *
     */
    public function testGetProductsTranslations()
    {
    }

    /**
     * Test case for getProductsVariationMatrix
     *
     * Get product variation matrix.
     *
     */
    public function testGetProductsVariationMatrix()
    {
    }

    /**
     * Test case for indexProduct
     *
     * Index products..
     *
     */
    public function testIndexProduct()
    {
    }

    /**
     * Test case for indexProductVariationOption
     *
     * Index product variation option.
     *
     */
    public function testIndexProductVariationOption()
    {
    }

    /**
     * Test case for indexProductsDraft
     *
     * Index products draft.
     *
     */
    public function testIndexProductsDraft()
    {
    }

    /**
     * Test case for indexProductsVariation
     *
     * Index products variation.
     *
     */
    public function testIndexProductsVariation()
    {
    }

    /**
     * Test case for indexProductsVariationType
     *
     * Index products variation type.
     *
     */
    public function testIndexProductsVariationType()
    {
    }

    /**
     * Test case for publishProduct
     *
     * Publish product.
     *
     */
    public function testPublishProduct()
    {
    }

    /**
     * Test case for showProduct
     *
     * Show existing product.
     *
     */
    public function testShowProduct()
    {
    }

    /**
     * Test case for showProductVariationOption
     *
     * Show single product variation option.
     *
     */
    public function testShowProductVariationOption()
    {
    }

    /**
     * Test case for showProductsVariation
     *
     * Show single products variation.
     *
     */
    public function testShowProductsVariation()
    {
    }

    /**
     * Test case for showProductsVariationType
     *
     * Show single products variation type.
     *
     */
    public function testShowProductsVariationType()
    {
    }

    /**
     * Test case for storeProduct
     *
     * Create a new product.
     *
     */
    public function testStoreProduct()
    {
    }

    /**
     * Test case for storeProductVariationOption
     *
     * Create new product variation option.
     *
     */
    public function testStoreProductVariationOption()
    {
    }

    /**
     * Test case for storeProductsDraft
     *
     * Create new products draft.
     *
     */
    public function testStoreProductsDraft()
    {
    }

    /**
     * Test case for storeProductsVariation
     *
     * Create new products variation.
     *
     */
    public function testStoreProductsVariation()
    {
    }

    /**
     * Test case for storeProductsVariationType
     *
     * Create new products variation type.
     *
     */
    public function testStoreProductsVariationType()
    {
    }

    /**
     * Test case for updateProduct
     *
     * Update existing product.
     *
     */
    public function testUpdateProduct()
    {
    }

    /**
     * Test case for updateProductVariationOption
     *
     * Update existing product variation option.
     *
     */
    public function testUpdateProductVariationOption()
    {
    }

    /**
     * Test case for updateProductsTranslations
     *
     * Update product translation.
     *
     */
    public function testUpdateProductsTranslations()
    {
    }

    /**
     * Test case for updateProductsVariation
     *
     * Update existing products variation.
     *
     */
    public function testUpdateProductsVariation()
    {
    }

    /**
     * Test case for updateProductsVariationType
     *
     * Update existing products variation type.
     *
     */
    public function testUpdateProductsVariationType()
    {
    }
}
